[package]
name = "ribn-cli"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = []
cuda = ["dep:ribn-text", "ribn-text/cuda"]

[dependencies]
ribn-text = { path = "../text", optional = true }
engine-gguf = { path = "../gguf" }

[lints]
workspace = true

[[bin]]
name = "ribn"
path = "src/main.rs"
doc = false
