[package]
name = "engine-gguf"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
engine-core = { path = "../core" }
minijinja = { version = "2.24.0", features = ["fuel", "json"] }
minijinja-contrib = { version = "2.24.0", features = ["pycompat"] }
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }

[lints]
workspace = true
